/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewReleasesRouteImport } from './routes/new-releases'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as SeriesSeriesIdRouteImport } from './routes/series/$seriesId'
import { Route as MoviesMovieIdRouteImport } from './routes/movies/$movieId'

const NewReleasesRoute = NewReleasesRouteImport.update({
  id: '/new-releases',
  path: '/new-releases',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesIdRoute = SeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-list': typeof MyListRoute
  '/new-releases': typeof NewReleasesRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/movies/': typeof MoviesIndexRoute
  '/series/': typeof SeriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-list': typeof MyListRoute
  '/new-releases': typeof NewReleasesRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/movies': typeof MoviesIndexRoute
  '/series': typeof SeriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-list': typeof MyListRoute
  '/new-releases': typeof NewReleasesRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/movies/': typeof MoviesIndexRoute
  '/series/': typeof SeriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-list'
    | '/new-releases'
    | '/movies/$movieId'
    | '/series/$seriesId'
    | '/movies/'
    | '/series/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-list'
    | '/new-releases'
    | '/movies/$movieId'
    | '/series/$seriesId'
    | '/movies'
    | '/series'
  id:
    | '__root__'
    | '/'
    | '/my-list'
    | '/new-releases'
    | '/movies/$movieId'
    | '/series/$seriesId'
    | '/movies/'
    | '/series/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyListRoute: typeof MyListRoute
  NewReleasesRoute: typeof NewReleasesRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  SeriesSeriesIdRoute: typeof SeriesSeriesIdRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-releases': {
      id: '/new-releases'
      path: '/new-releases'
      fullPath: '/new-releases'
      preLoaderRoute: typeof NewReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId': {
      id: '/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof SeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyListRoute: MyListRoute,
  NewReleasesRoute: NewReleasesRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  SeriesSeriesIdRoute: SeriesSeriesIdRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
